### ISSUE TITLE
Support optional depth argument

### ISSUE THREAD

**Issue by aweary** [sindresorhus/unique-random#1]
Currently `unique-random` only guarantees a unique random value at a depth of 1 in the call history. We can potentially add a third optional argument `depth` where users can specifiy how many calls deep the returned value should be compared against. So something like

``` js
var rand = uniqueRandom(1, 10, 3);
```

would mean that the returned value would be unique relative to the last 3 calls.

I'm just wondering if this is something you'd be interested in supporting. If so I can PR. I can fork it otherwise.

**Comment by sindresorhus** [comment]
Why? What do you need it for?

**Comment by aweary** [comment]
Using the same slideshow example, you could specify how many pictures in a row are unique. Avoiding possible scenarios like `picture1 => picture3 => picture1`

**Comment by sindresorhus** [comment]
I think this would make more sense as a separate module.

**Comment by aweary** [comment]
For reference:  [Aweary/unique-random-at-depth](https://github.com/Aweary/unique-random-at-depth)
