### ISSUE TITLE
They repeat... LOL

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/unique-random#13]
Heya. I haven't been much active for a long time.

Just tired that package and.. man, several runs and always get a duplicates.

```js
const random = uniqueRandom(1, 100);

console.log(
    Array(30)
        .fill(0)
        .map(() => random())
        .sort((a, b) => a - b)
);
```

outputs

```
[
   1,  7,   7, 10, 11, 12, 13, 24, 27,
  38, 39,  41, 43, 47, 51, 52, 59, 62,
  66, 67,  68, 70, 72, 82, 82, 84, 85,
  94, 99, 100
]
```

this one is not sorted, but at least the 83 is repeated.

```
[
  41, 16, 61,  2, 30, 56, 71, 20, 24,
  53, 73, 47, 23, 68, 14, 83, 47, 13,
  77, 16, 59, 43, 80, 79, 83, 30, 52,
  12, 97,  7
]
```

Am I that unlucky or what? :laughing: 

Maybe a better way would be the `previousValue` to be something like `temp` array instead and lookup on it.

**Comment by sindresorhus** [comment]
This package returns **consecutive random** numbers. It does this correctly. But since you are sorting the numbers, you end up with consecutive duplicates.

**Comment by tunnckoCore** [comment]
The second one doesn't sort them, yet i have 83 there 2 times.

**Comment by sindresorhus** [comment]
I don't think you understand the what "consecutive" means. What you want is being done in https://github.com/sindresorhus/unique-random/pull/12
