### ISSUE TITLE
Test when min == max

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/unique-random#26]
(theoretically) If they are equal then the previous value will always be the same, so the program enters an infinite loop.

I think it is a better fix to make it work with only one number anyways, as opposed to throwing an error since this could happen if min and max are generated by another source.

**Comment by Richienb** [comment]
Nevermind, this issue is dealt with, but there are no tests.

https://github.com/sindresorhus/unique-random/blob/c1a6a94a3a9e42cfde15682dca171f74afb81af1/index.js#L9

**Comment by Richienb** [comment]
How bad is it that we're outputting the same number in a row in a package where we say that we don't do that?

**Comment by sindresorhus** [comment]
I would say that should be expected when only one number is possible, but I think we should document that just to cover our bases, and obviously add a test for it.
