### ISSUE TITLE
Why write this in such a "clever" way?

### ISSUE THREAD

**Issue by dsernst** [sindresorhus/unique-random#3]
I was reviewing this function's code, and was surprised by how dense it was written. Just curious if you still support this style of code. (2 and a half years is 20-20?)

Admittedly it is perfectly effective, just far from readable. Like [this line](https://github.com/sindresorhus/unique-random/blob/8044a77a06b53a155539d2f2797e466896e0ad70/index.js#L6):

```js
return prev = num === prev && min !== max ? rand() : num;
```

😄

**Comment by sindresorhus** [comment]
I've improved the readability a little bit (How I would have written it today): https://github.com/sindresorhus/unique-random/commit/d04c01604f7574b1f4b0da4b0c17cf8924a2a309#diff-168726dbe96b3ce427e7fedce31bb0bc

I'm curious, how would you have written it?
