### ISSUE TITLE
same value?

### ISSUE THREAD

**Issue by woodgear** [sindresorhus/unique-random#5]
```
const uniqueRandom = require("unique-random")

const random = uniqueRandom(0, 2);

console.log(random(), random(), random());
```

**Comment by sindresorhus** [comment]
Not clear what you're asking.

**Comment by woodgear** [comment]
run this code under https://npm.runkit.com/unique-random mutli times. output could be below
```
1
0
1
```
and that is not unique

**Comment by sindresorhus** [comment]
Per the package description:

> Generate random numbers that are **consecutively** unique

It only guarantees that the numbers are consecutively unique.
