### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by nivzelber** [sindresorhus/unique-random#8]
Just installed the package, cool idea BTW!
Unfortunately I think it's not working correctly.
the following code:
```
import uniqueRandom from "unique-random";

const random = uniqueRandom(1, 4);
console.log(random(), random(), random(), random());
```
sometimes has bad results (i.e 1, 2, 4, 2 or 4, 1, 3, 4). I've noticed it's never the same number twice in a row if that's helpfull.

**Comment by sindresorhus** [comment]
What is incorrect exactly?

From the description:

> Generate random numbers that are **consecutively unique**

**Comment by nivzelber** [comment]
My bad. I was looking for a package that will return a different number from the range in each `random()` call.
You can close this issue.

**Comment by sindresorhus** [comment]
I'm open to having that ability added, but I don't plan to work on this myself. https://github.com/sindresorhus/unique-random/issues/9
