### ISSUE TITLE
Add option to use all number from the range before repeating any numbers

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/unique-random#9]
This can be useful, for example, for a music shuffle functionality. It should also ensure numbers across boundaries don't overlap. This would also be useful for slideshows to ensure the images don't show like "image A, image F, image A, …".

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt in https://github.com/sindresorhus/unique-random/pull/12

**Comment by Richienb** [comment]
Note to self: Maybe `export default function uniqueRandom` -> `export function consecutiveUniqueRandom` & `export function exhaustiveUniqueRandom`
